"""Fix reviews table schema

Revision ID: 5f8faadc3b13
Revises: c6d7b1872cba
Create Date: 2024-12-19 12:09:50.022536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8faadc3b13'
down_revision: Union[str, None] = 'c6d7b1872cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'reviews', ['uid'])
    op.drop_constraint('reviews_user_uid_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['uid'])
    op.drop_column('reviews', 'user_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_user_uid_fkey', 'reviews', 'users', ['user_uid'], ['uid'])
    op.drop_constraint(None, 'reviews', type_='unique')
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###
